import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SocketProvider } from "../context/SocketProvider";
// import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <SocketProvider>
      <html lang="en">
        <head />
        <body
          className={
            // twMerge(
            inter.className
            // , "")
          }
        >
          {children}
        </body>
      </html>
    </SocketProvider>
  );
}
